In [1]:
import numpy as np
import pandas as pd 

lap=pd.read_csv("laptops.csv",encoding='latin1')
lap=lap.rename(columns={'Price (Euros)':'price'})# renaming the price column
lap['price']=lap['price'].str.replace(",",'.')
lap['price'] =pd.to_numeric(lap['price'])
del lap['Operating System Version']# delating a column
lap['Screen Size'] =lap['Screen Size'].str.replace('"','')
lap['Screen Size'] =pd.to_numeric(lap['Screen Size'])

In [2]:
lap.head(2)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Weight,price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [4]:
# exercise 
# find the biggest and smallest screen size in laptops of each company using the sort_values() and duplicated ()
# methods (keep "first " ,"last " and false)

In [16]:
partition=lap.sort_values(['Screen Size','Manufacturer'])

In [27]:
partition.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Weight,price
50,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Android,0.69kg,319.00
1082,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Windows,0.69kg,646.27
1114,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Android,0.69kg,549.00
1126,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Windows,0.69kg,479.00
944,Lenovo,Yoga 700-11ISK,2 in 1 Convertible,11.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core M m7-6Y75 1.2GHz,8GB,256GB SSD,Intel HD Graphics 515,Windows,1.1kg,1299.00

In [31]:
partition.drop_duplicates(['Manufacturer'],keep='first')[['Manufacturer','Screen Size']]# smallest screen

     Manufacturer  Screen Size
50         Lenovo         10.1
319          Acer         11.6
1234        Apple         11.6
20           Asus         11.6
455          Dell         11.6
677            HP         11.6
429      Mediacom         11.6
430       Samsung         11.6
421         Chuwi         12.3
437        Google         12.3
816         Razer         12.5
963       Toshiba         12.5
170        Huawei         13.0
1120         Vero         13.3
192        Xiaomi         13.3
70      Microsoft         13.5
909            LG         14.0
785           MSI         14.0
567       Fujitsu         15.6

In [30]:
partition.drop_duplicates(['Manufacturer'],keep='last')[['Manufacturer','Screen Size']]# companies with biggest screen size

     Manufacturer  Screen Size
762        Google         12.3
214        Huawei         13.0
670     Microsoft         13.5
718      Mediacom         14.0
1041         Vero         14.0
17          Apple         15.4
483         Chuwi         15.6
983       Fujitsu         15.6
905            LG         15.6
593       Samsung         15.6
1042      Toshiba         15.6
514        Xiaomi         15.6
1216         Acer         17.3
1256         Asus         17.3
1243         Dell         17.3
1136           HP         17.3
1217       Lenovo         17.3
830         Razer         17.3
177           MSI         18.4