In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

df=df.dropna()# delete rows with any NaN values

In [2]:
df.head(3)

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     170
Velma Clemons   Biology  05/06/2016   43.0     167
kelly frye      Biology  05/06/2016   81.0     163

1 apply()

In [10]:
# use numpy function and it to series 
df['Marks'].apply([np.sqrt])

                        sqrt
Student Name
Vaibhav Kumar      10.000000
Velma Clemons       6.557439
kelly frye          9.000000
Louis Mcgee         3.316625
Phyllis Paul        4.242641
Zenaida Decker      7.416198
Gillian Tillman     6.164414
Constance Boone     4.000000
Giselle Lancaster   8.544004
Kirsten Mcdowell    4.000000

In [22]:
# create your own funcion and apply it to a df
# sum of all the marks 

def calculate_sum(row):
    return row['Marks']+row['Height']

In [23]:
df.apply(calculate_sum,axis=1)

Student Name
Vaibhav Kumar        270.0
Velma Clemons        210.0
kelly frye           244.0
Louis Mcgee          190.0
Phyllis Paul         171.0
Zenaida Decker       222.0
Gillian Tillman      208.0
Constance Boone      187.0
Giselle Lancaster    230.0
Kirsten Mcdowell     172.0
dtype: float64