In [4]:
# creating a dataframe from an array

In [3]:
import numpy as np 
import pandas as pd

In [13]:
data=np.array ([[1,2],[3,4],[6,7]])# creating an array

In [52]:
# creating a dataframe
pd.DataFrame(data)

   0  1
0  1  2
1  3  4
2  6  7

In [24]:
df=pd.DataFrame(data,index=['row1','row2','row3'],
                columns=['col1','col2'])

In [25]:
df

      col1  col2
row1     1     2
row2     3     4
row3     6     7

In [47]:
data2=np.array([['name','vaibhav'],['middle_name','Kumar'],['surname','Ram']])

In [58]:
d2=pd.DataFrame(data2,index=['R1','R2','R3'], columns=['I','II'])
# pd.DataFrame(data2)

In [59]:
d2

              I       II
R1         name  vaibhav
R2  middle_name    Kumar
R3      surname      Ram